/*
    NOTE: ALL POSITION VALUES ARE INCORRECT, THE FIRST 8 ROWS CONTAIN METADATA

    [{
        "id" : 211773290,
        "name" : "ID",
        "dataTypeName" : "text",
        "fieldName" : "id",
        "position" : 1,
        "renderTypeName" : "text",
        "tableColumnId" : 3297716,
    },{
        "id" : 211773291,
        "name" : "PERMIT#",
        "dataTypeName" : "text",
        "fieldName" : "permit_",
        "position" : 2,
        "renderTypeName" : "text",
        "tableColumnId" : 1450514,
      }, {
        "id" : 211773292,
        "name" : "  PERMIT_TYPE",
        "dataTypeName" : "text",
        "fieldName" : "_permit_type",
        "position" : 3,
        "rdfProperties" : "http://purl.org/dc/terms/type",
        "renderTypeName" : "text",
        "tableColumnId" : 1449867,
      }, {
        "id" : 211773293,
        "name" : "         ISSUE_DATE",
        "dataTypeName" : "calendar_date",
        "fieldName" : "_issue_date",
        "position" : 4,
        "rdfProperties" : "http://purl.org/dc/terms/date",
        "renderTypeName" : "calendar_date",
        "tableColumnId" : 1449868,
      }, {
        "id" : 211773294,
        "name" : "        ESTIMATED_COST",
        "dataTypeName" : "money",
        "fieldName" : "_estimated_cost",
        "position" : 5,
        "renderTypeName" : "money",
        "tableColumnId" : 1450515,
      }, {
        "id" : 211773295,
        "name" : "         AMOUNT_WAIVED",
        "dataTypeName" : "money",
        "description" : "Fee amount waived by City Council ordinance",
        "fieldName" : "_amount_waived",
        "position" : 6,
        "renderTypeName" : "money",
        "tableColumnId" : 1450517,
      }, {
        "id" : 211773296,
        "name" : "   AMOUNT_PAID",
        "dataTypeName" : "money",
        "description" : "Fee amount customer has paid.",
        "fieldName" : "_amount_paid",
        "position" : 7,
        "renderTypeName" : "money",
        "tableColumnId" : 1450516,
    }, {
        "id" : 211773297,
        "name" : "    TOTAL_FEE",
        "dataTypeName" : "money",
        "description" : "The amount waived plus amount paid plus any amount that may still be outstanding. This total can include various fees that are part of the permit fee, such as zoning, open space, deposit, or missed appointment.  It can also include stop work order fees, reinspection fees, and various penalty fees.",
        "fieldName" : "_total_permit_fee",
        "position" : 8,
        "renderTypeName" : "money",
        "tableColumnId" : 1450518,
      }, {
        "id" : 211773298,
        "name" : "STREET_NUMBER",
        "dataTypeName" : "number",
        "fieldName" : "street_number",
        "position" : 9,
        "renderTypeName" : "number",
        "tableColumnId" : 1449873,
      }, {
        "id" : 211773299,
        "name" : "STREET DIRECTION",
        "dataTypeName" : "text",
        "fieldName" : "street_direction",
        "position" : 10,
        "renderTypeName" : "text",
        "tableColumnId" : 1449874,
      }, {
        "id" : 211773300,
        "name" : "STREET_NAME",
        "dataTypeName" : "text",
        "fieldName" : "street_name",
        "position" : 11,
        "renderTypeName" : "text",
        "tableColumnId" : 1449875,
      }, {
        "id" : 211773301,
        "name" : "  SUFFIX",
        "dataTypeName" : "text",
        "fieldName" : "_suffix",
        "position" : 12,
        "renderTypeName" : "text",
        "tableColumnId" : 1449876,
      }, {
        "id" : 211773302,
        "name" : "WORK_DESCRIPTION",
        "dataTypeName" : "text",
        "fieldName" : "work_description",
        "position" : 13,
        "renderTypeName" : "text",
        "tableColumnId" : 1449878,
      }, {
        "id" : 211773303,
        "name" : "   PIN1",
        "dataTypeName" : "text",
        "fieldName" : "_pin1",
        "position" : 14,
        "renderTypeName" : "text",
        "tableColumnId" : 1449879,
      }, {
        "id" : 211773304,
        "name" : "   PIN2",
        "dataTypeName" : "text",
        "fieldName" : "_pin2",
        "position" : 15,
        "renderTypeName" : "text",
        "tableColumnId" : 1449880,
      }, {
        "id" : 211773305,
        "name" : "  PIN3",
        "dataTypeName" : "text",
        "fieldName" : "_pin3",
        "position" : 16,
        "renderTypeName" : "text",
        "tableColumnId" : 1449881,
      }, {
        "id" : 211773306,
        "name" : "  PIN4",
        "dataTypeName" : "text",
        "fieldName" : "_pin4",
        "position" : 17,
        "renderTypeName" : "text",
        "tableColumnId" : 1449882,
      }, {
        "id" : 211773307,
        "name" : " PIN5",
        "dataTypeName" : "text",
        "fieldName" : "_pin5",
        "position" : 18,
        "renderTypeName" : "text",
        "tableColumnId" : 1449883,
      }, {
        "id" : 211773308,
        "name" : " PIN6",
        "dataTypeName" : "text",
        "fieldName" : "_pin6",
        "position" : 19,
        "renderTypeName" : "text",
        "tableColumnId" : 1449884,
      }, {
        "id" : 211773309,
        "name" : " PIN7",
        "dataTypeName" : "text",
        "fieldName" : "_pin7",
        "position" : 20,
        "renderTypeName" : "text",
        "tableColumnId" : 1449885,
      }, {
        "id" : 211773310,
        "name" : " PIN8",
        "dataTypeName" : "text",
        "fieldName" : "_pin8",
        "position" : 21,
        "renderTypeName" : "text",
        "tableColumnId" : 1449886,
      }, {
        "id" : 211773311,
        "name" : " PIN9",
        "dataTypeName" : "text",
        "fieldName" : "_pin9",
        "position" : 22,
        "renderTypeName" : "text",
        "tableColumnId" : 1449887,
      }, {
        "id" : 211773312,
        "name" : "     PIN10",
        "dataTypeName" : "text",
        "fieldName" : "_pin10",
        "position" : 23,
        "renderTypeName" : "text",
        "tableColumnId" : 1449888,
      }, {
        "id" : 211773313,
        "name" : "CONTRACTOR_1_TYPE",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_type",
        "position" : 24,
        "renderTypeName" : "text",
        "tableColumnId" : 1449889,
      }, {
        "id" : 211773314,
        "name" : "CONTRACTOR_1_NAME",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_name",
        "position" : 25,
        "renderTypeName" : "text",
        "tableColumnId" : 1449890,
      }, {
        "id" : 211773315,
        "name" : "CONTRACTOR_1_ADDRESS",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_address",
        "position" : 26,
        "renderTypeName" : "text",
        "tableColumnId" : 1449891,
      }, {
        "id" : 211773316,
        "name" : "CONTRACTOR_1_CITY",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_city",
        "position" : 27,
        "renderTypeName" : "text",
        "tableColumnId" : 1449892,
      }, {
        "id" : 211773317,
        "name" : "CONTRACTOR_1_STATE",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_state",
        "position" : 28,
        "renderTypeName" : "text",
        "tableColumnId" : 1449893,
      }, {
        "id" : 211773318,
        "name" : "CONTRACTOR_1_ZIPCODE",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_zipcode",
        "position" : 29,
        "renderTypeName" : "text",
        "tableColumnId" : 1449894,
      }, {
        "id" : 211773319,
        "name" : "CONTRACTOR_1_PHONE",
        "dataTypeName" : "text",
        "fieldName" : "contractor_1_phone",
        "position" : 30,
        "renderTypeName" : "text",
        "tableColumnId" : 1449895,
      }, {
        "id" : 211773418,
        "name" : "LATITUDE",
        "dataTypeName" : "number",
        "fieldName" : "latitude",
        "position" : 129,
        "renderTypeName" : "number",
        "tableColumnId" : 3297756,
      }, {
        "id" : 211773419,
        "name" : "LONGITUDE",
        "dataTypeName" : "number",
        "fieldName" : "longitude",
        "position" : 130,
        "renderTypeName" : "number",
        "tableColumnId" : 3297757,
      }, {
        "id" : 211773420,
        "name" : "LOCATION",
        "dataTypeName" : "location",
        "fieldName" : "location",
        "position" : 131,
        "renderTypeName" : "location",
        "tableColumnId" : 3297758, 
      }
    ]
*/

/*
    SAMPLE ROW
    {
        0: 1, 
        1: "B24640A5-8BD2-44D7-AFA7-63CE2C9A5A41", 
        2: 1, 
        3: 1436247532, 
        4: "902270", 
        5: 1436247532, 
        6: "902270", 
        7: "{\n}", 
        8: "911610", 
        9: "EV000008", 
        10: "PERMIT - ELEVATOR EQUIPMENT", 
        11: null, 
        12: "0.00", 
        13: "0.00", 
        14: "52.50", 
        15: "52.50", 
        16: "406", 
        17: "N", 
        18: "ABERDEEN", 
        19: "ST", 
        20: null, 
        21: null, 
        22: null, 
        23: null, 
        24: null, 
        25: null, 
        26: null, 
        27: null, 
        28: null, 
        29: null, 
        30: null, 
        31: null, 
        32: null, 
        33: null, 
        34: null, 
        35: null, 
        36: null, 
        37: null, 
        38: null, 
        39: null, 
        ...,
        136: "41.889203998", 
        137: "-87.654722141", 
        138: [ null, "41.88920399822612", "-87.65472214051763", null, false ] 
    }
*/

(function() {
    'use strict';

    const CENTS_MULTIPLIER = 100;
    const DATE_COL = 11;
    const LAT_COL = 136;
    const LON_COL = 137;
    const DESC_COL = 20;
    const AMOUNT_COL = 15;
    const TYPE_COL = 10;

    module.exports = function(id) {
        return {
            id: () => id,
            type: (arr) => arr[TYPE_COL],
            status: (arr) =>  null,
            latitude: (arr) => arr[LAT_COL],
            longitude: (arr) => arr[LON_COL],
            units: () => null,
            timestamp: (arr) => arr[DATE_COL],
            description: (arr) => arr[DESC_COL],
            amount: (arr) => arr[AMOUNT_COL] * CENTS_MULTIPLIER
        };
    };

}());